# /home/amy/gdw2026/manufaktur/.server/manufaktur-server/docker-compose.yml
services:
  manufaktur-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /home/gdw/.manufaktur:/home/app/.manufaktur
      - .:/src