variables:
  EXPORT_NAME: Template
  GODOT_VERSION: mono-4.6.1


cache:
  key: import-${GODOT_VERSION}
  paths:
    - .godot/imported/

stages:
  - import-assets
  - export
  - deploy

import-assets:
  stage: import-assets
  image: barichello/godot-ci:${GODOT_VERSION}
  script:
    - godot --headless --verbose --editor --quit
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - .godot

.export:
  stage: export
  image: barichello/godot-ci:${GODOT_VERSION}
  dependencies:
    - import-assets
  before_script:
    - mkdir -v -p $EXPORT_NAME
    - EXPORT_DIR="$(readlink -f $EXPORT_NAME)"
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - $EXPORT_NAME


linux:
  extends: .export
  script:
    - godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/$EXPORT_NAME.x86_64"

windows:
  extends: .export
  script:
    - godot --headless --verbose --export-release "Windows" "$EXPORT_DIR/$EXPORT_NAME.exe"

mac:
  extends: .export
  script:
    - godot --headless --verbose --export-release "macOS" "$EXPORT_DIR/$EXPORT_NAME.zip"

